import type { Config } from 'tailwindcss';
import plugin from 'tailwindcss/plugin';
import animate from 'tailwindcss-animate';
import { addDynamicIconSelectors } from '@iconify/tailwind';
import aspectRatioPlugin from '@tailwindcss/aspect-ratio';
import typographyPlugin from '@tailwindcss/typography';
import { round } from './theme/lib';

import skillIconSetExtIcons from './icon-sets/skill-icons-ext/icons.json';

import {
  customTypography,
  customUtilities,
  customComponents,
  colors,
  breakpoints,
  spacing,
  radius,
  shadow,
  transition,
  fontSizes,
  fontFamily,
  widthSetup,
  animation,
  keyframes,
} from './theme';
import { globalCssVariables } from './global-css-variables';

export const tailwindConfig: Partial<Config> = {
  darkMode: ['class', '[data-theme="dark"]'], // custom class instead of default 'dark'
  theme: {
    fontSize: fontSizes,
    // transition parts
    ...transition,
    // own screens
    screens: breakpoints,
    // Border radius (.rounded-xxx)
    borderRadius: radius,
    spacing: spacing.all,
    boxShadow: shadow,
    aspectRatio: {
      ...Array.from(Array(21).keys()).reduce((acc, curr) => {
        return {
          ...acc,
          [`${curr + 1}`]: `${curr + 1}`, // from 1 to 21
        };
      }, {}),
    },
    extend: {
      colors,
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      fontFamily: {
        ...fontFamily,
        sans: fontFamily.default, // alias
      },
      width: widthSetup,
      maxWidth: widthSetup,
      minWidth: widthSetup,
      flexBasis: widthSetup,
      keyframes,
      animation,
      // Add custom variants
      lineHeight: {
        ...Array.from({ length: 100 }, (_, i) => round(1 + i * 0.01)).reduce(
          (acc, curr) => {
            return {
              ...acc,
              // usage: leading-1-5 (line-height: 1.5)
              // from v3.3 you may use text-sm/1-5
              [`${curr}`.replace('.', '-')]: `${curr}`,
            };
          },
          {},
        ),
      },
    },
  },
  plugins: [
    aspectRatioPlugin,
    typographyPlugin(),
    animate,
    // Iconify plugin
    addDynamicIconSelectors({
      prefix: 'icon',
      overrideOnly: true,
      iconSets: {
        'skill-icons-ext': skillIconSetExtIcons,
      },
    }),

    // Adding custom utilities here
    plugin((cfg) => {
      const { addComponents, addUtilities, addBase } = cfg;

      customComponents.map((cmp) => addComponents(cmp()));
      customUtilities.map((cmp) => addUtilities(cmp()));

      addComponents(customTypography);
      // Instead of default container, use custom one, css vars generated by config
      addComponents([
        {
          '.container': {
            maxWidth: 'var(--container-max-width)',
            paddingLeft: 'var(--container-padding)',
            paddingRight: 'var(--container-padding)',
            marginLeft: 'auto',
            marginRight: 'auto',
          },
        },
      ]);

      addBase({
        ':root': {
          ...globalCssVariables(),
        },
        'html, body': {
          minWidth: 'var(--min-document-width)',
        },
        body: {
          fontFamily: 'var(--font-family-default)',
          fontSize: 'var(--font-size-md)',
          background: 'var(--root-background-color)',
          color: 'var(--root-color)',
          lineHeight: 'normal',
          textDecorationSkipInk: 'none',
        },
      });
    }),
  ],
  corePlugins: {
    aspectRatio: false,
    container: false,
  },
};
